services:
  db:
    image: postgres:12
    container_name: notes-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_PASSWORD: secret
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: notes-api:dev
    container_name: notes-api
    environment:
      DB_HOST: db ## same as the database service name
      DB_DATABASE: notesdb
      DB_PASSWORD: secret
    volumes:
      - /home/node/app/node_modules
      - ./api:/home/node/app
    ports:
      - 3000:3000

volumes:
  db-data:
    name: notes-db-data
