services:
  #Webservers
   webserver:
     image: nginx:alpine
     restart: unless-stopped
     expose:
       - "80"
       - "443"
  #Load Balancer
   loadbalancer:
     image: nginx:alpine
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
       - webserver
     ports:
       - "80:4000"