#!/bin/bash

# Author:Christian Fröchtenicht fc1(at)gmx.net
# License: MIT
# Version: 1.0.0
# CreateDate: 20240514 ISO
# EditDate: 20240514 ISO
# Name: 8_password
# Description: check the first argument as password as format 8 items with letters and digist
if [ $# -ne 1 ]; then
	echo "expext one argument"
fi
if [[ "$1" =~ ^(.*[a-zA-Z].*[0-9].*|[0-9].*[a-zA-Z].*)$ && ${#1} -ge 8 ]]; then
	echo "ok"
fi


