services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INIT_DATABASE=todos_db
  api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - .env
networks:
  app-network:
    driver: bridge
volumes:
  data:
    driver: local