#!/usr/bin/python3

# Author:Christian Fröchtenicht fc1(at)gmx.net
# License: MIT
# Version: 1.0.0
# CreateDate: 20240604-111717 ISO
# EditDate: 20240604-111717 ISO
# Name: a4.py
# Description: ---

string=input("gebe Text ein:\n")
print(string[::-1])
