#!/usr/bin/python3

# Author:Christian Fröchtenicht fc1(at)gmx.net
# License: MIT
# Version: 1.0.0
# CreateDate: 20240604-112542 ISO
# EditDate: 20240604-112542 ISO
# Name: a7
# Description: ---

string=input("gebe ein palindrom ein:\n")
if string == string[::-1]:
    print("ja das ein palindrom: " + string)
